//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commanding.Tests.AcceptanceTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlIdentifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlIdentifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Commanding.Tests.AcceptanceTest.TestData.ControlIdentifiers", typeof(ControlIdentifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateLabel.
        /// </summary>
        internal static string DateLabel_Wpf {
            get {
                return ResourceManager.GetString("DateLabel_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryDateTextBox.
        /// </summary>
        internal static string DeliveryDateTextBox_Wpf {
            get {
                return ResourceManager.GetString("DeliveryDateTextBox_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell.
        /// </summary>
        internal static string DesktopApplicationTitle {
            get {
                return ResourceManager.GetString("DesktopApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string OrderListView_Wpf {
            get {
                return ResourceManager.GetString("OrderListView_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNameLabel.
        /// </summary>
        internal static string OrderNameLabel_Wpf {
            get {
                return ResourceManager.GetString("OrderNameLabel_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceLabel.
        /// </summary>
        internal static string PriceLabel_Wpf {
            get {
                return ResourceManager.GetString("PriceLabel_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceTextBox.
        /// </summary>
        internal static string PriceTextBox_Wpf {
            get {
                return ResourceManager.GetString("PriceTextBox_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityLabel.
        /// </summary>
        internal static string QuantityLabel_Wpf {
            get {
                return ResourceManager.GetString("QuantityLabel_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityTextBox.
        /// </summary>
        internal static string QuantityTextBox_Wpf {
            get {
                return ResourceManager.GetString("QuantityTextBox_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAllToolBarButton.
        /// </summary>
        internal static string SaveAllToolBarButton_Wpf {
            get {
                return ResourceManager.GetString("SaveAllToolBarButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveButton.
        /// </summary>
        internal static string SaveButton_Wpf {
            get {
                return ResourceManager.GetString("SaveButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingLabel.
        /// </summary>
        internal static string ShippingLabel_Wpf {
            get {
                return ResourceManager.GetString("ShippingLabel_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingTextBox.
        /// </summary>
        internal static string ShippingTextBox_Wpf {
            get {
                return ResourceManager.GetString("ShippingTextBox_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalLabel.
        /// </summary>
        internal static string TotalLabel_Wpf {
            get {
                return ResourceManager.GetString("TotalLabel_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalTextBox.
        /// </summary>
        internal static string TotalTextBox_Wpf {
            get {
                return ResourceManager.GetString("TotalTextBox_Wpf", resourceCulture);
            }
        }
    }
}
