//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAggregation.Tests.AcceptanceTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlIdentifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlIdentifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventAggregation.Tests.AcceptanceTest.TestData.ControlIdentifiers", typeof(ControlIdentifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivityLabel.
        /// </summary>
        internal static string ActivityLabel {
            get {
                return ResourceManager.GetString("ActivityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivityLabel.
        /// </summary>
        internal static string ActivityLabel_Wpf {
            get {
                return ResourceManager.GetString("ActivityLabel_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivityLabel.
        /// </summary>
        internal static string ActivityLabelId_Wpf {
            get {
                return ResourceManager.GetString("ActivityLabelId_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity for:.
        /// </summary>
        internal static string ActivityLabelTextValue {
            get {
                return ResourceManager.GetString("ActivityLabelTextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity for:.
        /// </summary>
        internal static string ActivityLabelTextValue_Wpf {
            get {
                return ResourceManager.GetString("ActivityLabelTextValue_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        internal static string ActivityView_Wpf {
            get {
                return ResourceManager.GetString("ActivityView_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddButton.
        /// </summary>
        internal static string AddButton_Wpf {
            get {
                return ResourceManager.GetString("AddButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundB.
        /// </summary>
        internal static string AnotherFund_Wpf {
            get {
                return ResourceManager.GetString("AnotherFund_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentPanel.
        /// </summary>
        internal static string ContentPanel_Wpf {
            get {
                return ResourceManager.GetString("ContentPanel_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer1.
        /// </summary>
        internal static string Customer1_Wpf {
            get {
                return ResourceManager.GetString("Customer1_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer1ComboItem.
        /// </summary>
        internal static string Customer1ComboItem_Wpf {
            get {
                return ResourceManager.GetString("Customer1ComboItem_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer2.
        /// </summary>
        internal static string Customer2_Wpf {
            get {
                return ResourceManager.GetString("Customer2_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerCbx.
        /// </summary>
        internal static string CustomerCombo {
            get {
                return ResourceManager.GetString("CustomerCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerCbx.
        /// </summary>
        internal static string CustomerCombo_Wpf {
            get {
                return ResourceManager.GetString("CustomerCombo_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerCbx.
        /// </summary>
        internal static string CustomerComboBox_old {
            get {
                return ResourceManager.GetString("CustomerComboBox_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerCombobox.
        /// </summary>
        internal static string CustomerCombobox_Wpf {
            get {
                return ResourceManager.GetString("CustomerCombobox_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer1.
        /// </summary>
        internal static string DefaultCustomer_Wpf {
            get {
                return ResourceManager.GetString("DefaultCustomer_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundA.
        /// </summary>
        internal static string DefaultFund_Wpf {
            get {
                return ResourceManager.GetString("DefaultFund_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell.
        /// </summary>
        internal static string DesktopApplicationTitle {
            get {
                return ResourceManager.GetString("DesktopApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundA.
        /// </summary>
        internal static string Fund1_Wpf {
            get {
                return ResourceManager.GetString("Fund1_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundB.
        /// </summary>
        internal static string Fund2_Wpf {
            get {
                return ResourceManager.GetString("Fund2_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundCbx.
        /// </summary>
        internal static string FundCombo {
            get {
                return ResourceManager.GetString("FundCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundCbx.
        /// </summary>
        internal static string FundCombo_Wpf {
            get {
                return ResourceManager.GetString("FundCombo_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundCbx.
        /// </summary>
        internal static string FundCombobox_Wpf {
            get {
                return ResourceManager.GetString("FundCombobox_Wpf", resourceCulture);
            }
        }
    }
}
