//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAggregation.Tests.AcceptanceTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestDataInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestDataInput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventAggregation.Tests.AcceptanceTest.TestData.TestDataInput", typeof(TestDataInput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer2.
        /// </summary>
        internal static string AnotherCustomer {
            get {
                return ResourceManager.GetString("AnotherCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundB.
        /// </summary>
        internal static string AnotherFund {
            get {
                return ResourceManager.GetString("AnotherFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer1.
        /// </summary>
        internal static string Customer0 {
            get {
                return ResourceManager.GetString("Customer0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer2.
        /// </summary>
        internal static string Customer1 {
            get {
                return ResourceManager.GetString("Customer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity for: Customer1.
        /// </summary>
        internal static string Customer1ActivityLabelText {
            get {
                return ResourceManager.GetString("Customer1ActivityLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity for: Customer2.
        /// </summary>
        internal static string Customer2ActivityLabelText {
            get {
                return ResourceManager.GetString("Customer2ActivityLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer1.
        /// </summary>
        internal static string DefaultCustomer {
            get {
                return ResourceManager.GetString("DefaultCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundA.
        /// </summary>
        internal static string DefaultFund {
            get {
                return ResourceManager.GetString("DefaultFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundA.
        /// </summary>
        internal static string Fund0 {
            get {
                return ResourceManager.GetString("Fund0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundB.
        /// </summary>
        internal static string Fund1 {
            get {
                return ResourceManager.GetString("Fund1", resourceCulture);
            }
        }
    }
}
