//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateBasedNavigation.Tests.AcceptanceTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlIdentifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlIdentifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StateBasedNavigation.Tests.AcceptanceTest.TestData.ControlIdentifiers", typeof(ControlIdentifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvatarButton.
        /// </summary>
        internal static string AvatarButton_Wpf {
            get {
                return ResourceManager.GetString("AvatarButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        internal static string AvatarButtonContent {
            get {
                return ResourceManager.GetString("AvatarButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvatarsView.
        /// </summary>
        internal static string AvatarsView {
            get {
                return ResourceManager.GetString("AvatarsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvatarsView.
        /// </summary>
        internal static string AvatarsView_Wpf {
            get {
                return ResourceManager.GetString("AvatarsView_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo.
        /// </summary>
        internal static string Combo_Wpf {
            get {
                return ResourceManager.GetString("Combo_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string ContactDetails_Wpf {
            get {
                return ResourceManager.GetString("ContactDetails_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State-Based Navigation.
        /// </summary>
        internal static string DesktopApplicationTitle {
            get {
                return ResourceManager.GetString("DesktopApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailsHeading.
        /// </summary>
        internal static string DetailsHeading_Wpf {
            get {
                return ResourceManager.GetString("DetailsHeading_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailsView.
        /// </summary>
        internal static string DetailsView_Wpf {
            get {
                return ResourceManager.GetString("DetailsView_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisconnectedImage.
        /// </summary>
        internal static string DisconnectedImage_Wpf {
            get {
                return ResourceManager.GetString("DisconnectedImage_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactImage.
        /// </summary>
        internal static string FriendImage_Wpf {
            get {
                return ResourceManager.GetString("FriendImage_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string FriendsList_Wpf {
            get {
                return ResourceManager.GetString("FriendsList_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListButton.
        /// </summary>
        internal static string ListButton_Wpf {
            get {
                return ResourceManager.GetString("ListButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ListButtonContent {
            get {
                return ResourceManager.GetString("ListButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxMessage.
        /// </summary>
        internal static string MessageTextBox_Wpf {
            get {
                return ResourceManager.GetString("MessageTextBox_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendMessageButton.
        /// </summary>
        internal static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SendButtonContent {
            get {
                return ResourceManager.GetString("SendButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendMessageButton.
        /// </summary>
        internal static string SendMessageButton_Wpf {
            get {
                return ResourceManager.GetString("SendMessageButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendMessageOkButton.
        /// </summary>
        internal static string SendMessageOkButton_Wpf {
            get {
                return ResourceManager.GetString("SendMessageOkButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendMessageChildWindow.
        /// </summary>
        internal static string SendMessageWindow_Wpf {
            get {
                return ResourceManager.GetString("SendMessageWindow_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxMessage.
        /// </summary>
        internal static string TextBoxMessage_Wpf {
            get {
                return ResourceManager.GetString("TextBoxMessage_Wpf", resourceCulture);
            }
        }
    }
}
