//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModularityWithMef.Tests.AcceptanceTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlIdentifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlIdentifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModularityWithMef.Tests.AcceptanceTest.TestData.ControlIdentifiers", typeof(ControlIdentifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click to load).
        /// </summary>
        internal static string ClickToLoadTextBlock {
            get {
                return ResourceManager.GetString("ClickToLoadTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modularity with MEF QuickStart - Desktop.
        /// </summary>
        internal static string DesktopApplicationTitle {
            get {
                return ResourceManager.GetString("DesktopApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleAAutomationId.
        /// </summary>
        internal static string ModuleA_Wpf {
            get {
                return ResourceManager.GetString("ModuleA_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleBAutomationId.
        /// </summary>
        internal static string ModuleB_Wpf {
            get {
                return ResourceManager.GetString("ModuleB_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleCAutomationId.
        /// </summary>
        internal static string ModuleC_Wpf {
            get {
                return ResourceManager.GetString("ModuleC_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleDAutomationId.
        /// </summary>
        internal static string ModuleD_Wpf {
            get {
                return ResourceManager.GetString("ModuleD_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleEAutomationId.
        /// </summary>
        internal static string ModuleE_Wpf {
            get {
                return ResourceManager.GetString("ModuleE_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleFAutomationId.
        /// </summary>
        internal static string ModuleF_Wpf {
            get {
                return ResourceManager.GetString("ModuleF_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleAutomationId.
        /// </summary>
        internal static string Modules_Wpf {
            get {
                return ResourceManager.GetString("Modules_Wpf", resourceCulture);
            }
        }
    }
}
