//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTraderRI.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTraderRI.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert from type {0} to enum type {1}.  The source value must be a string type..
        /// </summary>
        internal static string CannotConvertFromTypeToEnum {
            get {
                return ResourceManager.GetString("CannotConvertFromTypeToEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter should be convertible to an integer..
        /// </summary>
        internal static string CannotConvertParameterToIntegerException {
            get {
                return ResourceManager.GetString("CannotConvertParameterToIntegerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior cannot be attached to a null Region..
        /// </summary>
        internal static string InvalidAttachedRegion {
            get {
                return ResourceManager.GetString("InvalidAttachedRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply ActivateViewOnFocusBehavior to a Region that contains Views that are not UIElement..
        /// </summary>
        internal static string InvalidViewOnActivateViewOnFocusBehavior {
            get {
                return ResourceManager.GetString("InvalidViewOnActivateViewOnFocusBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have a public property named &apos;{1}&apos;. The current implementation of &apos;{2}&apos; does not allow specifying a nested path or a member that is not a property..
        /// </summary>
        internal static string SelectorExtensionCannotResolveMember {
            get {
                return ResourceManager.GetString("SelectorExtensionCannotResolveMember", resourceCulture);
            }
        }
    }
}
