

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "XamlGeneratedNamespace")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "StockTraderRI.ChartControls.ChartLines.#HorizontalAxisTickPositions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "StockTraderRI.ChartControls.ChartLines.#VerticalAxisTickPositions_CollectionChanged(System.Object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "StockTraderRI.ChartControls.ChartLines.#VerticalAxisTickPositions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StockTraderRI.ChartControls.ChartLines.#VerticalAxisTickPositions_CollectionChanged(System.Object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "arrangeBounds", Scope = "member", Target = "StockTraderRI.ChartControls.ClipWedge.#GetClipGeometry(System.Windows.Size)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "StockTraderRI.ChartControls.ClipWedge.#r")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "StockTraderRI.ChartControls.ColorConverter.#ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxis.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Seperation", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxis.#ReferenceLineSeperation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Seperation", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxis.#ReferenceLineSeperationProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxis.#SourceValues")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxis.#TickPositions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxis.#Values")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxisPanel.#_parentControl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxisPanel.#Axis2Panel_CollectionChanged(System.Object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.Double.ToString", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxisPanel.#GenerateItemsSource()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxisPanel.#Axis2Panel_CollectionChanged(System.Object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "labelSize", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxisPanel.#CalculatePixelIncrements(System.Windows.Size,System.Windows.Size)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxisPanel.#CalculateValueIncrement(System.Windows.Size)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "e", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxisPanel.#OnDataValuesChanged(System.Windows.DependencyObject,System.Windows.DependencyPropertyChangedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Seperation", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxisPanel.#ReferenceLineSeperation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Seperation", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxisPanel.#ReferenceLineSeperationProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "StockTraderRI.ChartControls.ContinuousAxisPanel.#YValues")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "StockTraderRI.ChartControls.DiscreteAxis.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "StockTraderRI.ChartControls.DiscreteAxis.#TickPositions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "rectHeight", Scope = "member", Target = "StockTraderRI.ChartControls.DiscreteAxisPanel.#ArrangeHorizontalLabels(System.Windows.Size)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "rectWidth", Scope = "member", Target = "StockTraderRI.ChartControls.DiscreteAxisPanel.#ArrangeVerticalLabels(System.Windows.Size)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "StockTraderRI.ChartControls.DiscreteAxisPanel.#TickPositions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors", Scope = "type", Target = "StockTraderRI.ChartControls.GeometryOperation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Catmull", Scope = "member", Target = "StockTraderRI.ChartControls.GeometryOperation.#CatmullRom(System.Windows.Point[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "StockTraderRI.ChartControls.GeometryOperation.#ComputeIntersectionPoint(System.Windows.FrameworkElement,System.Windows.FrameworkElement)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t", Scope = "member", Target = "StockTraderRI.ChartControls.GeometryOperation.#FindOppositePoint(System.Windows.Media.PathGeometry,System.Windows.Point,System.Windows.Vector,System.Windows.Media.Transform)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "StockTraderRI.ChartControls.LabelExtractor.#Items")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "newItems", Scope = "member", Target = "StockTraderRI.ChartControls.LabelExtractor.#OnItemsChanged(System.Windows.DependencyObject,System.Windows.DependencyPropertyChangedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "StockTraderRI.ChartControls.LineChart.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "newItems", Scope = "member", Target = "StockTraderRI.ChartControls.LineChartPanel.#OnValuesChanged(System.Windows.DependencyObject,System.Windows.DependencyPropertyChangedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "StockTraderRI.ChartControls.PieChart.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "StockTraderRI.ChartControls.PiePanel.#ParentControl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StockTraderRI.ChartControls.PiePanel.#PiePanel_CollectionChanged(System.Object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "StockTraderRI.ChartControls.PiePanel.#PiePanel_CollectionChanged(System.Object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "StockTraderRI.ChartControls.ValueExtractor.#Items")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "newItems", Scope = "member", Target = "StockTraderRI.ChartControls.ValueExtractor.#OnItemsChanged(System.Windows.DependencyObject,System.Windows.DependencyPropertyChangedEventArgs)")]
